// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	repositories "github.com/Koshsky/subs-service/auth-service/internal/repositories"
	mock "github.com/stretchr/testify/mock"
)

// DatabaseInterface is an autogenerated mock type for the DatabaseInterface type
type DatabaseInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: value
func (_m *DatabaseInterface) Create(value interface{}) repositories.DatabaseInterface {
	ret := _m.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 repositories.DatabaseInterface
	if rf, ok := ret.Get(0).(func(interface{}) repositories.DatabaseInterface); ok {
		r0 = rf(value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.DatabaseInterface)
		}
	}

	return r0
}

// First provides a mock function with given fields: dest, conds
func (_m *DatabaseInterface) First(dest interface{}, conds ...interface{}) repositories.DatabaseInterface {
	var _ca []interface{}
	_ca = append(_ca, dest)
	_ca = append(_ca, conds...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for First")
	}

	var r0 repositories.DatabaseInterface
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) repositories.DatabaseInterface); ok {
		r0 = rf(dest, conds...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.DatabaseInterface)
		}
	}

	return r0
}

// GetError provides a mock function with no fields
func (_m *DatabaseInterface) GetError() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Where provides a mock function with given fields: query, args
func (_m *DatabaseInterface) Where(query interface{}, args ...interface{}) repositories.DatabaseInterface {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Where")
	}

	var r0 repositories.DatabaseInterface
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) repositories.DatabaseInterface); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.DatabaseInterface)
		}
	}

	return r0
}

// NewDatabaseInterface creates a new instance of DatabaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatabaseInterface {
	mock := &DatabaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
