// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRabbitMQConn is an autogenerated mock type for the IRabbitMQConn type
type IRabbitMQConn struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *IRabbitMQConn) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIRabbitMQConn creates a new instance of IRabbitMQConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRabbitMQConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRabbitMQConn {
	mock := &IRabbitMQConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
